# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # you may remove this if you don't use vgo
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
  - <<: &build_defaults
      main: ./cmd/gli/main.go
      env:
        - CGO_ENABLED=0
    id: macos
    goos: [darwin]
    goarch: [amd64]
  - <<: *build_defaults
    id: linux
    goos: [linux]
    goarch: [386, amd64]
  - <<: *build_defaults
    id: windows
    goos: [windows]
    goarch: [386, amd64]
archives:
- replacements:
    darwin: MacOS
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
  files:
    - config.yml
    - success.html

github_urls:
  api: https://github.com/api/v3/
  upload: https://github.com/api/uploads/
  download: https://github.com/